defaults:
- override hydra/job_logging: colorlog
- override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

name: conv_phase2_game_result
## WANDB params
# The wandb project name
project: Lux_AI_2021
# The wandb user to log to
entity: isaiahpressman
# The wandb group for the run
group: after_september_patch

## ENV params
act_space: BasicActionSpace
obs_space: FixedShapeContinuousObsV2
obs_space_kwargs:
  include_subtask_encoding: False
reward_space: GameResultReward
reward_space_kwargs: {}

## TRAINING params
total_steps: 1e7
num_actors: 2
n_actor_envs: 16
unroll_length: 16
batch_size: 4
discounting: 0.999

## MODEL params
model_arch: conv_model
n_blocks: 8
hidden_dim: 128
embedding_dim: 32
n_merge_layers: 1
normalize: False
sum_player_embeddings: False
use_index_select: False
rescale_value_input: True
rescale_se_input: True
# Conv-specific params
kernel_size: 5


## OPTIMIZER params
optimizer_class: Adam
optimizer_kwargs:
  lr: 1e-4
  # See https://arxiv.org/pdf/2105.05246.pdf
  eps: 0.0003
  #alpha: 0.9
min_lr_mod: 0.01

## LOSS params
entropy_cost: 0.001
baseline_cost: 1.
teacher_kl_cost: 0.005
# lambda parameter for TD-lambda and UPGO losses
lmb: 0.8
reduction: sum

# MISCELLANEOUS params
actor_device: cuda:0
learner_device: cuda:0
disable_wandb: False
model_log_freq: 100
# file_descriptor or file_system
sharing_strategy: file_descriptor

# Continue from previous run
load_dir: <FOLDER_CONTAINING_TRAINED_PHASE1_MODEL> # E.g. .../outputs/09-01/09-58-50/
checkpoint_file: <MODEL_WEIGHTS_FILE> # E.g. 05079552.pt
weights_only: True
n_value_warmup_batches: 4000
