defaults:
- override hydra/job_logging: default
- override hydra/hydra_logging: default

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

# Parameters to overwrite
total_steps: 9e8
batch_size: 8
checkpoint_freq: 60.
#teacher_load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/11-18/20-32-30/
#teacher_checkpoint_file: 26530944.pt

# Continue from previous run
load_dir: /home/rick/IdeaProjects/Kaggle_Lux_AI_2021/outputs/12-24/16-10-50
checkpoint_file: 00998400.pt
weights_only: False

# Convenience for debugging
#disable_wandb: False
#debug: False